# SPDX-License-Identifier: Apache-2.0
broker.node.id=1
broker.local.host.port=127.0.0.1:19101
broker.group.name=order-management-java
broker.storage.path=/tmp/ringloom-framework-order-management/storage
broker.control.buffer.size=65536
broker.messages.buffer.size=1048576
broker.threading.mode=dedicated
broker.idle.strategy=backoff
broker.flow.control.enabled=true
broker.flow.control.peer.send.counters.enabled=true
