# SPDX-License-Identifier: Apache-2.0
ringloom:
  service:
    name: matching-engine
    storagePath: /tmp/ringloom-framework-order-management/storage
    group: order-management-java
  serializers:
    default: sbe
