# SPDX-License-Identifier: Apache-2.0
ringloom:
  service:
    name: order-gateway
    storagePath: /tmp/ringloom-framework-order-management-avaje/storage
    group: order-management-java-avaje
  serializers:
    default: fory
