# SPDX-License-Identifier: Apache-2.0
ringloom:
  service:
    name: market-terminal
    storagePath: /tmp/ringloom-framework-market-data-avaje-sbe/storage
    group: market-data-java-avaje
  runtime:
    requests:
      maxPending: 1024
      defaultTimeoutMillis: 2000
  serializers:
    default: sbe
